name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: docs
          output_dir: pdfs
          images_dir: docs/images
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: readmepdf
          path: pdfs